language: java
jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

cache:
  directories:
    - $HOME/.gradle/caches

#apt:
#  packages:
#    - python
#    - python-pip

script: gradle build

before_deploy:
  - mv build/libs/ci-cd-demo.jar bundle/test-app.jar
  - mkdir -p upload
  - cd bundle
  - zip -r ../upload/test-app.zip ./
  - cd ..
  - aws s3 cp upload/test-app.zip s3://xsolve-ci-cd-demo-codedeploy/test-app.zip --region eu-central-1

deploy:
#  - provider: s3
#    access_key_id: &1
#      secure: "Jz23i9gRoewgSSIT5nx4mK/6AL3e2yLmtBcouz+FpQkfUtI1v1wg/fZITXSpEvQ3rY3YTrAFsnVg1+hpMoLJ7prUf9U4DGMszvZm1a97A2s/iFD77wksgMKx3rVXAHU1v3y3QbE580oKcIVm0tWlog163NXoe4ThwOtFIX3Pd2tjDUB3Nuuho41TqvSMGNwEX8R+bo9wZUIQszK1xw3yx3MOuHQOGSGcjVPgAbKiCV6wlMJzSfZAzXtljHsFt3DQsq4C0R+SOJUrV1xigRoZJO6HM6k+JOhMjRTAPDmKPQ9tHeTwYDEFMqDLlQwY4zxJGBj+O4J8kn+NmGIhkGAnyabZw/lgSfitgyrF8inE/DFvV3GAwbO85KkuoD0dv4ivoSvwfT/M1U8tdJi4xAYyRk3I/O1ohtrcxiKMrxocOvskOqKT05tpNEGDDOUdr2pGm735dvkElo7f9qTTeDpMKlqzo4I4I9nGyyTp6qgl0cM0qIhnWDmJadlrWck3YB9qnrMXu5p1kA+eKCuRkC1PKRsQz3de3a4TIwTIS4hH3avTjQSrDvB1UZPJ2Whw8zDZw+CAzBQMyIRpmPd3CJu+IpQuakubhChH7KeQVgIkbh9yw3tgb+3vxFFtRlBkil0r+nimcPEp6fk071d0AXmJEQLAYfkOGp+l9g+Ge2SatLs="
#    secret_access_key: &2
#      secure: "gDY3m4vgmAEemnIFvzpQCWiC1vX145WrwFMTKTUUw4Vfsjj7Dif7tJO6wz57CkyGNGXGL9bT6bQF2EaHgX5EWs8Kv7RDaEn0czb9YMdL2BHyJBUhDlw+oMVOLB/d7o3cRCOgyYm5jbS4ZPuNkrwDQpFPouEDE0qpTS4T/GXtKcDnVP1jxn6xL99K2cjS74oxxTdtfJwEnx8q3h6zseuMZ9+S0yLXz0jrTrWXEo9QepofBE4i4O+J4SEpRANgRr+lDXK1g1VipvcPmAm4rNfghCsIfeHI7nLV9QBhMbKR5rsNpdp2lK/Yoe7gVIjxUBtmYjwS1JJiteUolbPZ0IvOUiAWMYh/DX+1gE0VhSNs66jByTebzjv2HtZhK67Z2SjgCr5oNQwukDBsLb/HwY1/3qO6ijhClUu7pTXO3qeKTuOysfbKTHzVCLlYZ1FmmkMcWN4OQSufNtOiavhUn3sPS28OJcd91zGnlo7Pk8i+r2VPQ45Uh5RWFKe4AJyK4OD2GJjvW+Xmv0FTHobJtkzvJ5bZmEZtieDveBzDO914+IJGEhIimSYKnAQelT8Y1guel351UKwCpHWkkQpL2ckRRxB9n3r1bWVKsD1TQDLfOfJpn3NPfGZI2/6QAMCBnCY+88p2rdfiXkSF8TKwf8pT+JoJjxu39/aPM1pfaU8CJPY="
#    local_dir: dpl_cd_upload
#    skip_cleanup: true
#    on: &3
#      branch: master
#    bucket: xsolve-ci-cd-demo-codedeploy
#    region: eu-central-1
  - provider: codedeploy
#    access_key_id: *1
#    secret_access_key: *2
    bucket: xsolve-ci-cd-demo-codedeploy
    key: test-app.zip
    bundle_type: zip
    application: Demo-App
    deployment_group: test-deployment-group
    on:
      branch: master
    region: eu-central-1
    wait-until-deployed: true

env:
  global:
    - secure: "qTxeV1QetxffBoUXQ8SYE4iEH3E90k+GNgvAkzlx6Xsk2S2kITPywpVWAgZvR46lLLezCfCewWshDq35UFw4fEZEve4fBJzvvyvQ6UUgPKhjxdKdDKGyX+1HwwZklExhRTZXyPpFHN7JIsHFp29WijKoD9jT2GM912sP83d4Hur8N+0GLV4fxwJuoESisbi3IyRbzpL5Tgs8lsWmi5XpElpu6JviA9eavFD1Ips3s33sLX36Pd2nhmD/GDXnm8Bk8ZJQ+ecz71JMIjj/euA6yi2Aw5j7koLBrT/rGUoG+alo+HtN36IVTQVsFr116fN3yUjPI/oFk7T01sVVW4rmouH14ee8K1HZmM56SW8uHI41XbF922p0iAvJFIY9NlukJ2Zwl76CK+SMaVcnO2D4uLpNagi/QaVRZbU4oAYwMVlyATaFauoP1DM3MSsDbm0fqX66YK10xZeQFVzAXK+T4XWaeCeD6m5AvOxWMh4ijQphCJsaJ37c54tGrLex/fqN/vlbAP3ToXe+i8XH+blBoNNAQi1q8A6dDl0muNqjRRr9Ro5yt1DhHGCT+gp89hA3jQwTz1+yBWpuY7hsQ27qu/cPKEe4hkG9+53pFkmA0KD5VpM5vPLnROMlJ1CiOXFZLl2IPHV9UEVuqFH0szoq0fVaB1fBIx+PeUJzQ8zdFPI="
    - secure: "F6O9XCvEsk4EZHfrAcdhNd9m7uBZoZh8UnuoUP87Nb/HGeSKQpRWQxQ2kzqEv2uYkhHK4aJuG4sGThH2qzfxOgT53UZSsoNl+Y+Yij6j1jkohCqlXV4I8ELVwtn3bBjs/oJSHtAM7KnyeRmJVPTrMZl06epbAJjyB67Rk5BilcJdJf40Tu1jTaGay3145LK+VWazUDkF69O+ZBxU5gA5kdY/Cw/GZIMEWnBCNHtQjGP9IfjhHFIaOlJZ8nxxftAbj45dvDuQ051HU7ou1UTPY91KxUUZcchUgbi7Byw41Es6Cbv5R/JEWN2ysUVsZ8UfChfQTVydokYsSBjxKVxeQNbf87nJMrAosIxUxKcdDu73OD5aBHFvqZLNU3r1PcKS7ypIsuF2S5InGjlAsF6RGkUZAqHf6dDyPb7CL35UgFuDQ4aJ+lM3K+lcRQ5V/WHUsNWzBDJSjmXGBxorDI6nFRxS2ODs4jl+d++mrFxrIUMdT2+l3DgthiRPPfTvFuQ9uDpydI2HTZ2ZS2rI77AyZUBLvADBxgIDeX2JVWh3cK9XPVVDpzFo2UsruTIdBs4ortQErfoJzG23poambE58Q3lnzxF94SAIQOVpfAF29fZOJQH7TLV9D0/StwZH67Jdr9FPabjdViyS590p2FTnU7tJ7K1Z7b0Nq+PDXtx5QH8="
